name: Test Pipeline

on:
  push:
    branches: [ "demo" ]
  pull_request:
    types: [closed]
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci-be:
    if: |
      startsWith(github.event.head_commit.message, 'DEPLOY/FULL') || 
      startsWith(github.event.head_commit.message, 'DEPLOY/BE')
    runs-on: ubuntu-24.04
    steps:
      - name: test
        run: | 
          echo ${{github.event_name}}
