# name: Test Pipeline

# on:
# #   push:
# #     branches: [ "demo" ]
#   pull_request:
#     types: [closed]
#     branches: ["main"]
#   workflow_dispatch:


# jobs:
#   check-changes:
#     # if: |
#     #     github.event.pull_request.merged == true
#     # #   startsWith(github.event.head_commit.message, 'DEPLOY') ||
#     runs-on: ubuntu-24.04   
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Check if folder "my-folder" has changed
#         run: |
#           # Check for changes in the "my-folder" directory
#           git diff --exit-code --quiet HEAD~1 HEAD -- my-folder/
#         continue-on-error: true

#       - name: Run workflow if folder changed
#         if: ${{ steps.check-changes.outcome == 'failure' }}
#         run: |
#           echo "Folder 'my-folder' has changed. Running the rest of the pipeline."
#           # Add additional steps for the workflow here.

name: Test Pipeline

on:
  push:
    branches: [ "demo" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Check if 'src/' folder has changes
        run: |
          git fetch --prune --unshallow
          git diff --exit-code --quiet HEAD~1 HEAD -- src/
        continue-on-error: true  # To allow the workflow to continue even if changes are not found

      - name: Set output for folder change
        id: check_changes
        run: |
          if git diff --exit-code --quiet HEAD~1 HEAD -- src/; then
            echo "No changes in 'src/' folder."
            echo "folder_changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected in 'src/' folder."
            echo "folder_changed=true" >> $GITHUB_ENV
          fi

      - name: Display folder change status
        run: | 
          echo "Folder changed: $folder_changed"
